### PR TITLE
Added two sections: management package and client package

### PR DESCRIPTION
**Pull request by spelluru**
Added two sections: management package and client package with links to documentation for the packages

### CODE REVIEW

**Comment by spelluru** [comment]
#sign-off

**Comment by spelluru** [comment]
@scbedd - could you review and merge this PR when you get a chance? I got your name from another PR that was approved and merged by you, so I am pinging you :). If I should work with someone else, please let me know. Thanks!!

**Comment by scbedd** [comment]
Nope I'm on it. Thanks for the heads up.

**Comment by spelluru** [comment]
@scbedd - Thanks very much!!

**Pull request merged**
