### PR TITLE
remove /en-us/ in links

### PR DESCRIPTION
**Pull request by Saisang**

### CODE REVIEW

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/index.experimental.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/sai-removelocinfo0710/docs-ref-conceptual/index.experimental.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/azure/index.experimental?view=azure-node-latest&branch=pr-en-us-350) (azure-node-latest) |
[docs-ref-services/cognitive-services.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/sai-removelocinfo0710/docs-ref-services/cognitive-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/cognitive-services?view=azure-node-latest&branch=pr-en-us-350) (azure-node-latest) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C10%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201807102021264607-350%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=AnhYxIzpH9yxWmIbmgiyuRujBkNlTbGYJ%2BjpfeXbVyI%3D&st=2018-07-10T20%3A30%3A37Z&se=2018-08-10T20%3A35%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Saisang** [comment]
#sign-off

**Comment by JennieHubbard** [comment]
@thedanfernandez @dend

**Comment by rloutlaw** [comment]
approving and merging

**Pull request merged**
