### PR TITLE
Replace legacy build pipeline with Typescript SDP build pipeline

### PR DESCRIPTION
**Pull request by yunair**

### CODE REVIEW

**Comment by scbedd** [comment]
@yunair Are there any changes to CI? Will this work with the existing job?

**Comment by scbedd** [comment]
Can't directly merge because of conflicts due to the additional commits after ignite. Will pull these changes across manually and update CI build to use it.

**Comment by yunair** [comment]
trigger build

**Comment by scbedd** [comment]
Merging this and re-running CI. Thanks for the follow-up @yunair !

**Pull request merged**
