### PR TITLE
 Reassign reference articles to team-specific authors

### PR DESCRIPTION
**Pull request by craigshoemaker**
This PR assigns Node.js SDK articles to the following team-specific authors:

- @KumudD
- @Minewiskan
- @SyntaxC4
- @rloutlaw
- @eamonoreilly
- @markgalioto
- @tfitzmac
- @dksimpson
- @brapel
- @mmacy
- @SnehaGunda
- @craigcaseyMSFT
- @sethmanheim
- @mumian
- @dominicbetts
- @barclayn
- @ecfan
- @hning86
- @Juliako
- @MGoedtel
- @rachel-msft
- @markingmyname
- @wesmc7777
- @rwike77
- @bwren
- @rayne-wiselman
- @CarlRabeler
- @jimdial
- @iainfoulds

### CODE REVIEW

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** System.IO.FileNotFoundException: Could not find file &#39;W:\kdv4-s\docs-ref-services\other.md&#39;.
File name: &#39;W:\kdv4-s\docs-ref-services\other.md&#39;
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at JoinTOC.TOCMerger.AlterYamlHeader(String path, Action`1 handler)
   at JoinTOC.TOCMerger.HandleConceptualNode(TocItemViewModel tocItem, String tocFilePath)
   at JoinTOC.TOCMerger.Merge(CommandLineOptions opt)
   at JoinTOC.Program.Main(String[] args)
 - **Line 80**: **[Warning]** Failed to run script W:\kdv4-s\_dependentPackages\CommonPlugins\tools\JoinTOC.ps1 with exit code -1

<a name=""></a>
### []()
 - **[Error]** System.IO.FileNotFoundException: Could not find file &#39;W:\kdv4-s\docs-ref-services\other.md&#39;.
File name: &#39;W:\kdv4-s\docs-ref-services\other.md&#39;
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at JoinTOC.TOCMerger.AlterYamlHeader(String path, Action`1 handler)
   at JoinTOC.TOCMerger.HandleConceptualNode(TocItemViewModel tocItem, String tocFilePath)
   at JoinTOC.TOCMerger.Merge(CommandLineOptions opt)
   at JoinTOC.Program.Main(String[] args)
 - **Line 80**: **[Warning]** Failed to run script W:\kdv4-s\_dependentPackages\CommonPlugins\tools\JoinTOC.ps1 with exit code -1

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C4%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201805041535447699-315%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=PdrlCMG1BrqBqmmN2wnZSe21GtLCKShqrgyn%2BH9Z4zA%3D&st=2018-05-04T15%3A42%3A49Z&se=2018-06-04T15%3A47%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mimig1** [comment]
@craigshoemaker - @SnehaGunda is the new docs owner for Cosmos DB. Can you reassign to her?

**Comment by craigshoemaker** [comment]
@mimig1 done with commit 343678fdda3ac4b4558711ccab63c8a60a154d11

**Comment by mmacy** [comment]
@craigshoemaker ACR assignment LGTM

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** System.IO.FileNotFoundException: Could not find file &#39;W:\djbx-s\docs-ref-services\other.md&#39;.
File name: &#39;W:\djbx-s\docs-ref-services\other.md&#39;
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at JoinTOC.TOCMerger.AlterYamlHeader(String path, Action`1 handler)
   at JoinTOC.TOCMerger.HandleConceptualNode(TocItemViewModel tocItem, String tocFilePath)
   at JoinTOC.TOCMerger.Merge(CommandLineOptions opt)
   at JoinTOC.Program.Main(String[] args)
 - **Line 80**: **[Warning]** Failed to run script W:\djbx-s\_dependentPackages\CommonPlugins\tools\JoinTOC.ps1 with exit code -1

<a name=""></a>
### []()
 - **[Error]** System.IO.FileNotFoundException: Could not find file &#39;W:\djbx-s\docs-ref-services\other.md&#39;.
File name: &#39;W:\djbx-s\docs-ref-services\other.md&#39;
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at JoinTOC.TOCMerger.AlterYamlHeader(String path, Action`1 handler)
   at JoinTOC.TOCMerger.HandleConceptualNode(TocItemViewModel tocItem, String tocFilePath)
   at JoinTOC.TOCMerger.Merge(CommandLineOptions opt)
   at JoinTOC.Program.Main(String[] args)
 - **Line 80**: **[Warning]** Failed to run script W:\djbx-s\_dependentPackages\CommonPlugins\tools\JoinTOC.ps1 with exit code -1

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C4%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201805041735336512-315%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=SBxl3W%2BUluvo784N4KqZlZWa2BdPpq5WjAYIYERxTCM%3D&st=2018-05-04T17%3A43%3A25Z&se=2018-06-04T17%3A48%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by craigshoemaker** [comment]
re-opening to trigger a new build

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-services/activedirectory.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/activedirectory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/activedirectory?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/advisor.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/advisor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/advisor?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/analysis-services.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/analysis-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/analysis-services?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/appservice.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/appservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/appservice?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/authorization.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/authorization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/authorization?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/automation.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/automation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/automation?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/backup.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/backup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/backup?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/billing.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/billing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/billing?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/cdn.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/cdn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/cdn?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/cognitive-services.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/cognitive-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/cognitive-services?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/commerce.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/commerce.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/commerce?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/container-registry.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/container-registry.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/container-registry?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/cosmos-db.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/cosmos-db.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/cosmos-db?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/devtest-labs.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/devtest-labs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/devtest-labs?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/dns.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/dns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/dns?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/event-hub.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/event-hub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/event-hub?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/hdinsight.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/hdinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/hdinsight?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/iot-hub.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/iot-hub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/iot-hub?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/key-vault.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/key-vault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/key-vault?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/logic-apps.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/logic-apps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/logic-apps?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/machine-learning.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/machine-learning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/machine-learning?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/media-services.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/media-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/media-services?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/monitor.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/monitor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/monitor?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/mysql.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/mysql.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/mysql?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/notification-hubs.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/notification-hubs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/notification-hubs?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/operational-insights.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/operational-insights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/operational-insights?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/other.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/other.md) | :white_check_mark:Succeeded | |
[docs-ref-services/postgresql.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/postgresql.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/postgresql?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/powerbi-embedded.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/powerbi-embedded.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/powerbi-embedded?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/redis-cache.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/redis-cache.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/redis-cache?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/relay.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/relay.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/relay?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/resources.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/resources?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/scheduler.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/scheduler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/scheduler?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/search.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/search?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/server-management.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/server-management.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/server-management?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/service-bus.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/service-bus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/service-bus?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/service-fabric.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/service-fabric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/service-fabric?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/service-map.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/service-map.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/service-map?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/site-recovery.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/site-recovery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/site-recovery?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/sql.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/sql.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/sql?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/traffic-manager.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/traffic-manager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/traffic-manager?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/virtual-network.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/virtual-network.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/virtual-network?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |
[docs-ref-services/virtualmachines.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-ref-services-reassign/docs-ref-services/virtualmachines.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/virtualmachines?view=azure-node-latest&branch=pr-en-us-315) (azure-node-latest) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C16%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201805161928401147-315%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=uUCqZUSx1%2FyBRYR5e8ispLwO4vkHRnfplDaxySl5UiU%3D&st=2018-05-16T19%3A36%3A57Z&se=2018-06-16T19%3A41%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
