### PR TITLE
Update cosmos-db.md

### PR DESCRIPTION
**Pull request by JasonWHowell**
Fixing metadata

### CODE REVIEW

**Comment by JasonWHowell** [comment]
#sign-off

**Comment by JasonWHowell** [comment]
@Taojunshen Do you help merge in this repo? This one is ready.

**Comment by JasonWHowell** [comment]
@JiayueHu can you help merge in this repo? This one is ready.

**Comment by JasonWHowell** [comment]
@mmacy Do you know what's the process to merge in this repo? PRs have been sitting for about a week. Thanks, Jason

**Comment by mmacy** [comment]
@JasonWHowell Recommend you post to Docs Support.

**Pull request merged**
