### PR TITLE
Metadata corrections, refresh the introduction and links.

### PR DESCRIPTION
**Pull request by HeidiSteen**

### CODE REVIEW

**Comment by HeidiSteen** [comment]
#sign-off   pre-existing validation warnings are on content that I didn't touch.

**Comment by HeidiSteen** [comment]
#signoff

**Comment by HeidiSteen** [comment]
@rloutlaw Hi Robert, can you merge this PR?  Apologies if I should have followed a different process for content updates -- this isn't a repo that I plan to work in on a regular basis so I went with the Edit pencil for a small number of metadata and content edits.

**Comment by rloutlaw** [comment]
@HeidiSteen Thanks for the contribution. I'll merge and it will propagate to the live site on the next scheduled publish.

**Pull request merged**
