### PR TITLE
testing markdig

### PR DESCRIPTION
**Pull request by bowdenk7**

### CODE REVIEW

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/azure-docs-sdk-node, working directory: W:\qunh-s, target branch: master, target branch commit: e7566b123ba9765f8a5f504a29a00e4eadb81f30, source branch: markdigtest, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C31%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201807312255306294-355%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=alBDdgvJS83%2BJQ3zKjCE3R7mGSliw5O%2BFGcpV8s2B1U%3D&st=2018-07-31T22%3A51%3A07Z&se=2018-08-31T22%3A56%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docfx.json](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/markdigtest/docfx.json) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/index-preview.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/markdigtest/docs-ref-conceptual/index-preview.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/azure/index-preview?view=azure-node-latest&branch=pr-en-us-355) (azure-node-latest) |
[docs-ref-conceptual/index.experimental.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/markdigtest/docs-ref-conceptual/index.experimental.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/azure/index.experimental?view=azure-node-latest&branch=pr-en-us-355) (azure-node-latest) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C31%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201807312256176857-355%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=U8tDRWn5e7Fmbl1ey9ma%2FZTqTH6%2BhpZc0fJuBqhhMv8%3D&st=2018-07-31T23%3A22%3A37Z&se=2018-08-31T23%3A27%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docfx.json](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/markdigtest/docfx.json) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/index-preview.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/markdigtest/docs-ref-conceptual/index-preview.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/azure/index-preview?view=azure-node-latest&branch=pr-en-us-355) (azure-node-latest) |
[docs-ref-conceptual/index.experimental.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/markdigtest/docs-ref-conceptual/index.experimental.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/azure/index.experimental?view=azure-node-latest&branch=pr-en-us-355) (azure-node-latest) |
[docs-ref-conceptual/index2.experimental.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/markdigtest/docs-ref-conceptual/index2.experimental.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/azure/index2.experimental?view=azure-node-latest&branch=pr-en-us-355) (azure-node-latest) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C1%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201807312355189087-355%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=FMJuzgvNA69GQ4FGWp33LEb6VyxtfBPH0EqoP1PpFSg%3D&st=2018-08-01T00%3A19%3A37Z&se=2018-09-01T00%3A24%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dendeli-msft** [comment]
Closing out-of-date PR.

**Pull request closed without merging**
