### PR TITLE
Updated the note to migrate to Microsoft Graph

### PR DESCRIPTION
**Pull request by CelesteDG**
Removed links to samples that have been archived as we don't want customers to use this anymore.
Fixes https://github.com/MicrosoftDocs/azure-docs-sdk-node/issues/772

### CODE REVIEW

**Comment by CelesteDG** [comment]
#sign-off

**Comment by CelesteDG** [comment]
Flagging for @rloutlaw to review - Hi Robert, when you get a chance can you please take a look? I'm unsure about the file causing the warning. Thank you.

**Comment by scbedd** [comment]
@CelesteDG thanks! Merged.

**Comment by CelesteDG** [comment]
Thank you very much, @scbedd

**Pull request merged**
