### PR TITLE
Fix `data-table` typo

### PR DESCRIPTION
**Pull request by rugglcon**
[Relevant issue](https://github.com/Azure/azure-sdk-for-js/issues/27316#issue-1924665510)

The `@azure/data-tables` package is mislabeled as `data-table`. This PR just adds the 's'

### CODE REVIEW

**Comment by rugglcon** [comment]
@microsoft-github-policy-service agree

**Comment by saran-surya** [comment]
Hi @rugglcon 
I guess you will need to rebase the main branch.

**Review by EmmaZhu — APPROVED** [review]

**Comment by rugglcon** [comment]
@saran-surya rebased

**Comment by rugglcon** [comment]
@EmmaZhu you may need to approve again

**Comment by rugglcon** [comment]
@saran-surya needs approved again

**Review by xirzec — APPROVED** [review]

**Pull request merged**
