### PR TITLE
Adding redirect for renamed article

### PR DESCRIPTION
**Pull request by msmbaldwin**

### CODE REVIEW

**Comment by msmbaldwin** [comment]
Neither of the validation errors relate to the change I made. #sign-off

**Comment by msmbaldwin** [comment]
Who can review and merge this?  @scbedd, @Taojunshen.

**Comment by scbedd** [comment]
I gotcha @msmbaldwin

**Comment by msmbaldwin** [comment]
Thank you, @scbedd. Can we also merge master to live? https://github.com/MicrosoftDocs/azure-docs-sdk-node/pull/778

**Pull request merged**
