### PR TITLE
Adding billing option to TOC

### PR DESCRIPTION
**Pull request by itye-msft**

### CODE REVIEW

**Comment by mikekinsman** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/toc.yml](https://github.com/itye-msft/azure-docs-sdk-node/blob/master/docs-ref-conceptual/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/javascript/azure/node-samples-services-billing?view=azure-node-latest&branch=pr-en-us-274) (azure-node-latest) | [Details](#user-content-docs-ref-conceptual%2Ftoc.yml)
[docs-ref-conceptual/node-samples-services-billing.md](https://github.com/itye-msft/azure-docs-sdk-node/blob/master/docs-ref-conceptual/node-samples-services-billing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/azure/node-samples-services-billing?view=azure-node-latest&branch=pr-en-us-274) (azure-node-latest) |

<a name="docs-ref-conceptual%2Ftoc.yml"></a>
### [docs-ref-conceptual/toc.yml](https://github.com/itye-msft/azure-docs-sdk-node/blob/master/docs-ref-conceptual/toc.yml)
 - **[Warning]** TOC item (Href:node-samples-services-billing.md ) with empty name found. Missing a name?
 - **[Warning]** TOC item (Href:node-samples-services-billing.md ) with empty name found. Missing a name?

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C26%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201802261601442842-274%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=OtLP0Qq%2FaaRPuWWQtTcW78pJAVI9BvwAMhdiMGNy4b8%3D&st=2018-02-26T16%3A08%3A14Z&se=2018-03-29T16%3A13%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by tamram** [comment]
@itye-msft @craigshoemaker 

If you remove the "-" in front of "href" in the TOC.yml file, that should resolve the validation issue.

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/node-samples-services-billing.md](https://github.com/itye-msft/azure-docs-sdk-node/blob/master/docs-ref-conceptual/node-samples-services-billing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/azure/node-samples-services-billing?view=azure-node-latest&branch=pr-en-us-274) (azure-node-latest) |
[docs-ref-conceptual/toc.yml](https://github.com/itye-msft/azure-docs-sdk-node/blob/master/docs-ref-conceptual/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/javascript/azure/node-samples-services-billing?view=azure-node-latest&branch=pr-en-us-274) (azure-node-latest) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C28%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201802280552134404-274%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=iPhqKuddqK%2FlRE%2BLq%2FJvtGJ%2BKuAsVwj%2FnaYAROOglGU%3D&st=2018-02-28T06%3A00%3A08Z&se=2018-03-31T06%3A05%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by itye-msft** [comment]
Hi @tamram , thanks for pinpointing the error.
It's fixed and passed validation.
Can you please merge it?

**Comment by craigshoemaker** [comment]
#sign-off

**Comment by craigshoemaker** [comment]
@itye-msft there is a process that the PR has to go through before it's merged. I have added the appropriate keyword to kick off the procedure ;)

**Comment by itye-msft** [comment]
Thank you @craigshoemaker !
What else can I do to make it merge please?

**Comment by tamram** [comment]
@itye-msft @craigshoemaker - Because this is in the azure-docs-sdk-node repo, I am going to email the PR reviewers to find the right person to merge this.

**Pull request merged**
