### PR TITLE
Added sample for nodejs scheduler

### PR DESCRIPTION
**Pull request by sptramer**

### CODE REVIEW

**Comment by herohua** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/includes/scheduler-samples.md](https://github.com/sptramer/azure-docs-sdk-node/blob/scheduler-landing/docs-ref-conceptual/includes/scheduler-samples.md) | :white_check_mark:Succeeded | |
[docs-ref-services/scheduler.md](https://github.com/sptramer/azure-docs-sdk-node/blob/scheduler-landing/docs-ref-services/scheduler.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C10%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201707102325052350-51%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sptramer** [comment]
#sign-off

**Comment by TomArcher** [comment]
#hold-off 

@sptramer Please change this to match the new instructions 

**Management Package
...
***Install npm package
***Example
***Samples
...

And bullets instead of a table for the samples

**Comment by TomArcher** [comment]
@sptramer You have conflicts that need to be resolved

**Comment by herohua** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/index.yml](https://github.com/sptramer/azure-docs-sdk-node/blob/scheduler-landing/docs-ref-conceptual/index.yml) | :x:Error | | [Details](#user-content-docs-ref-conceptual%2Findex.yml)

<a name="docs-ref-conceptual%2Findex.yml"></a>
### [docs-ref-conceptual/index.yml](https://github.com/sptramer/azure-docs-sdk-node/blob/scheduler-landing/docs-ref-conceptual/index.yml)
 - **[Error]** File docs-ref-conceptual/index.yml with type LandingData doesn&#39;t have asset id. Please set it.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C13%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201707131827185753-51%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by herohua** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/index.yml](https://github.com/sptramer/azure-docs-sdk-node/blob/scheduler-landing/docs-ref-conceptual/index.yml) | :x:Error | | [Details](#user-content-docs-ref-conceptual%2Findex.yml)

<a name="docs-ref-conceptual%2Findex.yml"></a>
### [docs-ref-conceptual/index.yml](https://github.com/sptramer/azure-docs-sdk-node/blob/scheduler-landing/docs-ref-conceptual/index.yml)
 - **[Error]** File docs-ref-conceptual/index.yml with type LandingData doesn&#39;t have asset id. Please set it.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C13%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201707131829544848-51%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by TomArcher** [comment]
@sptramer Merged

**Pull request merged**
