### PR TITLE
update date of service-fabric.md

### PR DESCRIPTION
**Pull request by craigshoemaker**

### CODE REVIEW

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-services/service-fabric.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-refresh-service-fabric/docs-ref-services/service-fabric.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C12%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201711121317527687-229%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=TVssGy%2BmqLMqpY%2FOc%2Bz7rmQhP4qxMyYBp9gI3%2FJLdVA%3D&st=2017-11-12T13%3A22%3A14Z&se=2017-12-13T13%3A27%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by craigshoemaker** [comment]
#sign-off

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-services/service-fabric.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-refresh-service-fabric/docs-ref-services/service-fabric.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C12%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201711121807514460-229%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=bBkBUdlG3BD0TITV8veZrZD1x%2BGKV8HtOtZh17RP46E%3D&st=2017-11-12T18%3A12%3A24Z&se=2017-12-13T18%3A17%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-services/service-fabric.md](https://github.com/craigshoemaker/azure-docs-sdk-node/blob/crs-refresh-service-fabric/docs-ref-services/service-fabric.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C12%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201711121812544194-229%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0lWy8KQTRhegQXzd9uQ0vSuw6A0jTrEs2r3hUvqLdls%3D&st=2017-11-12T18%3A22%3A07Z&se=2017-12-13T18%3A27%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
