### PR TITLE
Update redis-cache.md

### PR DESCRIPTION
**Pull request by flang-msft**
This is part of this bug - 
https://dev.azure.com/msazure/RedisCache/_workitems/edit/13201686

### CODE REVIEW

**Comment by flang-msft** [comment]
#sign-off

**Comment by flang-msft** [comment]
#assign-reviewer: @flang-msft

**Review by flang-msft — COMMENTED** [review]
Code matches what I received from engineering

**Comment by flang-msft** [comment]
#assign: wesmc

**Comment by flang-msft** [comment]
#assign: flang-msft

**Comment by flang-msft** [comment]
#assign: @flang-msft

**Comment by flang-msft** [comment]
#please-close

**Review by wesmc7777 — APPROVED** [review]

**Comment by wesmc7777** [comment]
#sign-off

**Comment by flang-msft** [comment]
#sign-off

**Comment by flang-msft** [comment]
#please-open

**Comment by flang-msft** [comment]
@Taojunshen - I'm hoping you can help me merge and publish the PR. I didn't realize that the process for this public repo was different.

**Comment by flang-msft** [comment]
#sign-off

**Review by sima-zhu — APPROVED** [review]

**Pull request merged**
