### PR TITLE
Update Preview Documentation ToC

### PR DESCRIPTION
**Pull request by scbedd**
@ramya-rao-a There is something else going on with what we're seeing on the site. What we see here: https://docs.microsoft.com/en-us/javascript/api/overview/azure/?view=azure-node-preview doesn't actually align with the current settings for the ToC. 

For instance `@azure/storage-file-share` is definitely present, but isn't reflected on the currently published ToC.

Regardless, the CI is updated to what we expect (latest preview), and I've organized the below as well. If there are additional updates necessary i'll make them.

### CODE REVIEW

**Comment by ramya-rao-a** [comment]
@scbedd Can you specify as to which bug is being fixed by this PR because Event Hubs is still appearing under "Other" in https://docs.microsoft.com/en-us/javascript/api/overview/azure/?view=azure-node-preview

And the content is still v2 and not v5

**Comment by rloutlaw** [comment]
@ramya-rao-a  Master branch is not the public live site content. That is in the live branch.

Master branch, which this PR is merged into, is here:

https://review.docs.microsoft.com/en-us/javascript/api/@azure/event-hubs/?view=azure-node-preview&branch=master

**Comment by ramya-rao-a** [comment]
Thanks @rloutlaw, Event Hubs does show up in the right location in the toc in the link you have shared.

@scbedd Is getting preview content for `@azure/keyvault-certificates` and `@azure/storage-file-share` to show up also a matter of updating the `reference.yml` file like in this PR or is that a separate problem altogether?

**Comment by scbedd** [comment]
It's _like_ this change yes. The key here is to update the ToC for preview reference documentation, we need to submit PRs to change _this_ [reference.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/preview-packages/docs-ref-mapping/reference.yml) 

Note that it's under the `preview_packages` folder. This folder is the landing location for any of the preview generated documentation. I did some digging to figure out why the preview stuff wasn't updating with my ToC changes for it. Found that it was because the `git push` step of the job was disabled for testing by the doc dev team. I'm surprised that there is no `smoke-test-preview` branch now available after the run last night, so I'm checking on that.

**Pull request merged**
