### PR TITLE
Add or update the App Service deployment workflow configuration from …

### PR DESCRIPTION
**Pull request by chaos-ui**
…Azure Portal.

### CODE REVIEW

**Review by chaos-ui — COMMENTED** [review]
Is the package valid?

**Review by danieljurek — CHANGES_REQUESTED** [review]
What is the purpose of this change?

**Review by chaos-ui — COMMENTED** [review]
Azure LexiX application to be synced

**Comment by danieljurek** [comment]
@chaos-ui -- Can you expand on what this change is supposed to accomplish? This is a repository for Azure SDK for JavaScript reference documentation and this PR doesn't update files relating to that purpose.

**Review by chaos-ui — COMMENTED** [review]
All requirements met

**Comment by danieljurek** [comment]
Closing.

**Pull request closed without merging**
