### PR TITLE
Azure Monitor - Use monitor API

### PR DESCRIPTION
**Pull request by jawache**

### CODE REVIEW

**Comment by herohua** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-services/monitor.md](https://github.com/jawache/azure-docs-sdk-node/blob/patch-11/docs-ref-services/monitor.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C18%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201707181113225827-129%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jawache** [comment]
From some investigation I suspect Azure Monitor was renamed to Azure Insights, checking with the PM Andy Shen

**Comment by jawache** [comment]
FYI: I've changed the module from arm-insights to arm-module. 
This is verified after a long thread with the appropriate PM and devs. 
The monitor module does not use promises which is why the code sample is using a callback.

**Comment by johnpapa** [comment]
Can you list the PMs here?

**Comment by johnpapa** [comment]
#sign-off

**Comment by jawache** [comment]
For completeness the SME who confirmed to use the azure-arm-monitor package is Guillermo Calderon-Meza <gucalder@microsoft.com>.

**Pull request merged**
