### PR TITLE
Add 'overview' section to references.

### PR DESCRIPTION
**Pull request by sptramer**

### CODE REVIEW

**Comment by herohua** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-services/other.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/other.md) | :white_check_mark:Succeeded | |
[docs-ref-services/powerbi-embedded.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/powerbi-embedded.md) | :white_check_mark:Succeeded | |
[docs-ref-services/redis-cache.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/redis-cache.md) | :white_check_mark:Succeeded | |
[docs-ref-services/relay.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/relay.md) | :white_check_mark:Succeeded | |
[docs-ref-services/resources.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/resources.md) | :white_check_mark:Succeeded | |
[docs-ref-services/scheduler.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/scheduler.md) | :white_check_mark:Succeeded | |
[docs-ref-services/search.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/search.md) | :white_check_mark:Succeeded | |
[docs-ref-services/server-management.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/server-management.md) | :white_check_mark:Succeeded | |
[docs-ref-services/service-bus.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/service-bus.md) | :white_check_mark:Succeeded | |
[docs-ref-services/service-fabric.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/service-fabric.md) | :white_check_mark:Succeeded | |
[docs-ref-services/service-map.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/service-map.md) | :white_check_mark:Succeeded | |
[docs-ref-services/site-recovery.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/site-recovery.md) | :white_check_mark:Succeeded | |
[docs-ref-services/traffic-manager.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/traffic-manager.md) | :white_check_mark:Succeeded | |
[docs-ref-services/virtual-network.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/virtual-network.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C7%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201707071659362059-29%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by herohua** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/azure-docs-sdk-node, working directory: W:\okma-s, target branch: aug-1-stage, target branch commit: b8c63f432e86ddfa7e1fd575f8868bb1f436c0c6, source branch: 09bb737fc6a66b1fb713632e5595f970/landing-overview-updates, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C7%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201707071732257776-29%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by herohua** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** System.IO.FileNotFoundException: Could not find file &#39;W:\2j0z-s\docs-ref-services\advisor.md&#39;.
File name: &#39;W:\2j0z-s\docs-ref-services\advisor.md&#39;
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at JoinTOC.TOCMerger.AlterYamlHeader(String path, Action`1 handler)
   at JoinTOC.TOCMerger.HandleConceptualNode(TocItemViewModel tocItem, String tocFilePath)
   at JoinTOC.TOCMerger.Merge(CommandLineOptions opt)
   at JoinTOC.Program.Main(String[] args)
 - **Line 80**: **[Warning]** Failed to run script W:\2j0z-s\_dependentPackages\CommonPlugins\tools\JoinTOC.ps1 with exit code -1

<a name=""></a>
### []()
 - **[Error]** System.IO.FileNotFoundException: Could not find file &#39;W:\2j0z-s\docs-ref-services\advisor.md&#39;.
File name: &#39;W:\2j0z-s\docs-ref-services\advisor.md&#39;
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at JoinTOC.TOCMerger.AlterYamlHeader(String path, Action`1 handler)
   at JoinTOC.TOCMerger.HandleConceptualNode(TocItemViewModel tocItem, String tocFilePath)
   at JoinTOC.TOCMerger.Merge(CommandLineOptions opt)
   at JoinTOC.Program.Main(String[] args)
 - **Line 80**: **[Warning]** Failed to run script W:\2j0z-s\_dependentPackages\CommonPlugins\tools\JoinTOC.ps1 with exit code -1

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C7%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201707071742185103-29%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by herohua** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** System.IO.FileNotFoundException: Could not find file &#39;W:\vryu-s\docs-ref-services\advisor.md&#39;.
File name: &#39;W:\vryu-s\docs-ref-services\advisor.md&#39;
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at JoinTOC.TOCMerger.AlterYamlHeader(String path, Action`1 handler)
   at JoinTOC.TOCMerger.HandleConceptualNode(TocItemViewModel tocItem, String tocFilePath)
   at JoinTOC.TOCMerger.Merge(CommandLineOptions opt)
   at JoinTOC.Program.Main(String[] args)
 - **Line 80**: **[Warning]** Failed to run script W:\vryu-s\_dependentPackages\CommonPlugins\tools\JoinTOC.ps1 with exit code -1

<a name=""></a>
### []()
 - **[Error]** System.IO.FileNotFoundException: Could not find file &#39;W:\vryu-s\docs-ref-services\advisor.md&#39;.
File name: &#39;W:\vryu-s\docs-ref-services\advisor.md&#39;
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at JoinTOC.TOCMerger.AlterYamlHeader(String path, Action`1 handler)
   at JoinTOC.TOCMerger.HandleConceptualNode(TocItemViewModel tocItem, String tocFilePath)
   at JoinTOC.TOCMerger.Merge(CommandLineOptions opt)
   at JoinTOC.Program.Main(String[] args)
 - **Line 80**: **[Warning]** Failed to run script W:\vryu-s\_dependentPackages\CommonPlugins\tools\JoinTOC.ps1 with exit code -1

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C7%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201707071800534290-29%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by herohua** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-services/advisor.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/advisor.md) | :white_check_mark:Succeeded | |
[docs-ref-services/analysis-services.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/analysis-services.md) | :white_check_mark:Succeeded | |
[docs-ref-services/authorization.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/authorization.md) | :white_check_mark:Succeeded | |
[docs-ref-services/automation.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/automation.md) | :white_check_mark:Succeeded | |
[docs-ref-services/backup.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/backup.md) | :white_check_mark:Succeeded | |
[docs-ref-services/billing.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/billing.md) | :white_check_mark:Succeeded | |
[docs-ref-services/cdn.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/cdn.md) | :white_check_mark:Succeeded | |
[docs-ref-services/cognitive-services.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/cognitive-services.md) | :white_check_mark:Succeeded | |
[docs-ref-services/commerce.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/commerce.md) | :white_check_mark:Succeeded | |
[docs-ref-services/container-registry.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/container-registry.md) | :white_check_mark:Succeeded | |
[docs-ref-services/cosmos-db.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/cosmos-db.md) | :white_check_mark:Succeeded | |
[docs-ref-services/data-lake-analytics.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/data-lake-analytics.md) | :white_check_mark:Succeeded | |
[docs-ref-services/data-lake-store.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/data-lake-store.md) | :white_check_mark:Succeeded | |
[docs-ref-services/devtest-labs.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/devtest-labs.md) | :white_check_mark:Succeeded | |
[docs-ref-services/dns.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/dns.md) | :white_check_mark:Succeeded | |
[docs-ref-services/event-hub.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/event-hub.md) | :white_check_mark:Succeeded | |
[docs-ref-services/hdinsight.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/hdinsight.md) | :white_check_mark:Succeeded | |
[docs-ref-services/intune.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/intune.md) | :white_check_mark:Succeeded | |
[docs-ref-services/iot-hub.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/iot-hub.md) | :white_check_mark:Succeeded | |
[docs-ref-services/key-vault.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/key-vault.md) | :white_check_mark:Succeeded | |
[docs-ref-services/logic-apps.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/logic-apps.md) | :white_check_mark:Succeeded | |
[docs-ref-services/machine-learning.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/machine-learning.md) | :white_check_mark:Succeeded | |
[docs-ref-services/media-services.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/media-services.md) | :white_check_mark:Succeeded | |
[docs-ref-services/monitor.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/monitor.md) | :white_check_mark:Succeeded | |
[docs-ref-services/notification-hubs.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/notification-hubs.md) | :white_check_mark:Succeeded | |
[docs-ref-services/operational-insights.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/operational-insights.md) | :white_check_mark:Succeeded | |
[docs-ref-services/other.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/other.md) | :white_check_mark:Succeeded | |
[docs-ref-services/powerbi-embedded.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/powerbi-embedded.md) | :white_check_mark:Succeeded | |
[docs-ref-services/redis-cache.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/redis-cache.md) | :white_check_mark:Succeeded | |
[docs-ref-services/relay.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/relay.md) | :white_check_mark:Succeeded | |
[docs-ref-services/resources.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/resources.md) | :white_check_mark:Succeeded | |
[docs-ref-services/scheduler.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/scheduler.md) | :white_check_mark:Succeeded | |
[docs-ref-services/search.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/search.md) | :white_check_mark:Succeeded | |
[docs-ref-services/server-management.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/server-management.md) | :white_check_mark:Succeeded | |
[docs-ref-services/service-bus.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/service-bus.md) | :white_check_mark:Succeeded | |
[docs-ref-services/service-fabric.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/service-fabric.md) | :white_check_mark:Succeeded | |
[docs-ref-services/service-map.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/service-map.md) | :white_check_mark:Succeeded | |
[docs-ref-services/site-recovery.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/site-recovery.md) | :white_check_mark:Succeeded | |
[docs-ref-services/traffic-manager.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/traffic-manager.md) | :white_check_mark:Succeeded | |
[docs-ref-services/virtual-network.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/virtual-network.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C7%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201707071808042842-29%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by herohua** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-services/cdn.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/cdn.md) | :white_check_mark:Succeeded | |
[docs-ref-services/cognitive-services.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/cognitive-services.md) | :white_check_mark:Succeeded | |
[docs-ref-services/cosmos-db.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/cosmos-db.md) | :white_check_mark:Succeeded | |
[docs-ref-services/key-vault.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/key-vault.md) | :white_check_mark:Succeeded | |
[docs-ref-services/notification-hubs.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/notification-hubs.md) | :white_check_mark:Succeeded | |
[docs-ref-services/other.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/other.md) | :white_check_mark:Succeeded | |
[docs-ref-services/powerbi-embedded.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/powerbi-embedded.md) | :white_check_mark:Succeeded | |
[docs-ref-services/redis-cache.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/redis-cache.md) | :white_check_mark:Succeeded | |
[docs-ref-services/relay.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/relay.md) | :white_check_mark:Succeeded | |
[docs-ref-services/resources.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/resources.md) | :white_check_mark:Succeeded | |
[docs-ref-services/scheduler.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/scheduler.md) | :white_check_mark:Succeeded | |
[docs-ref-services/search.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/search.md) | :white_check_mark:Succeeded | |
[docs-ref-services/server-management.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/server-management.md) | :white_check_mark:Succeeded | |
[docs-ref-services/service-bus.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/service-bus.md) | :white_check_mark:Succeeded | |
[docs-ref-services/service-fabric.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/service-fabric.md) | :white_check_mark:Succeeded | |
[docs-ref-services/service-map.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/service-map.md) | :white_check_mark:Succeeded | |
[docs-ref-services/site-recovery.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/site-recovery.md) | :white_check_mark:Succeeded | |
[docs-ref-services/traffic-manager.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/traffic-manager.md) | :white_check_mark:Succeeded | |
[docs-ref-services/utf-cleanup.sh](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/utf-cleanup.sh) | :white_check_mark:Succeeded | |
[docs-ref-services/virtual-network.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/virtual-network.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C11%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201707111616315121-29%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by herohua** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-services/notification-hubs.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/notification-hubs.md) | :white_check_mark:Succeeded | |
[docs-ref-services/other.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/other.md) | :white_check_mark:Succeeded | |
[docs-ref-services/powerbi-embedded.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/powerbi-embedded.md) | :white_check_mark:Succeeded | |
[docs-ref-services/redis-cache.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/redis-cache.md) | :white_check_mark:Succeeded | |
[docs-ref-services/relay.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/relay.md) | :white_check_mark:Succeeded | |
[docs-ref-services/resources.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/resources.md) | :white_check_mark:Succeeded | |
[docs-ref-services/scheduler.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/scheduler.md) | :white_check_mark:Succeeded | |
[docs-ref-services/search.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/search.md) | :white_check_mark:Succeeded | |
[docs-ref-services/server-management.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/server-management.md) | :white_check_mark:Succeeded | |
[docs-ref-services/service-bus.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/service-bus.md) | :white_check_mark:Succeeded | |
[docs-ref-services/service-fabric.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/service-fabric.md) | :white_check_mark:Succeeded | |
[docs-ref-services/service-map.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/service-map.md) | :white_check_mark:Succeeded | |
[docs-ref-services/site-recovery.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/site-recovery.md) | :white_check_mark:Succeeded | |
[docs-ref-services/traffic-manager.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/traffic-manager.md) | :white_check_mark:Succeeded | |
[docs-ref-services/utf-cleanup.sh](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/utf-cleanup.sh) | :white_check_mark:Succeeded | |
[docs-ref-services/virtual-network.md](https://github.com/sptramer/azure-docs-sdk-node/blob/landing-overview-updates/docs-ref-services/virtual-network.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C11%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201707112323330163-29%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by TomArcher** [comment]
@sptramer Merged

**Pull request merged**
