### PR TITLE
update product name

### PR DESCRIPTION
**Pull request by dcurwin**
-------
cc: @VSC-Service-Account

### CODE REVIEW

**Comment by dcurwin** [comment]
#sign-off

**Comment by dcurwin** [comment]
@xirzec - Can you help get this published?

**Review by xirzec — APPROVED** [review]
do we have to re-release the package in order to do so?

**Comment by dcurwin** [comment]
> do we have to re-release the package in order to do so?

@xirzec  - I have no information about that. This isn't my repo. I'm just responsible for the documentation for Defender for Cloud Apps, and want to make sure the right term is used.

**Comment by xirzec** [comment]
> @xirzec - I have no information about that. This isn't my repo. I'm just responsible for the documentation for Defender for Cloud Apps, and want to make sure the right term is used.

Perhaps @diberry can remind me about the flow to get this published.

**Comment by diberry** [comment]
@xirzec My understanding is that this repo is owned by the Azure SDK team, not the Skilling org.

**Comment by xirzec** [comment]
> @xirzec My understanding is that this repo is owned by the Azure SDK team, not the Skilling org.

Oh wow, that's news to me. According to the internal tooling this repo is owned by @martinekuan and @barbkess -- not sure if we have some side agreement to own it, @kurtzeborn does EngSys own this repo? 😄

**Pull request merged**
