### PR TITLE
App Service - Fix links to samples

### PR DESCRIPTION
**Pull request by diberry**
Both of these repos have been archived - so maybe the better fix is to remove them @ramya-rao-a ?

### CODE REVIEW

**Comment by ramya-rao-a** [comment]
Both repos are over 5 years old, they must have been archived for a reason. If we can't get those reasons from the repo owners or if they don't add much value when compared to the other two samples, then my recommendation would be to remove them altogether

**Review by sima-zhu — APPROVED** [review]

**Review by ramya-rao-a — CHANGES_REQUESTED** [review]
This has been discussed offline with the appropriate teams and the decision was to remove these links altogether

**Comment by ramya-rao-a** [comment]
@diberry Are you planning to send a separate PR to remove the links? I assumed this same PR would be updated to do so :)

**Comment by diberry** [comment]
@ramya-rao-a  I didn't realize that comment was directed to me. Yes, I'll make that change.

**Review by ramya-rao-a — APPROVED** [review]

**Comment by ramya-rao-a** [comment]
Thanks @diberry!

**Pull request merged**
