### PR TITLE
copy edit

### PR DESCRIPTION
**Pull request by TomArcher**

### CODE REVIEW

**Comment by herohua** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/node-howto-e2e.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/deploy-article-copy-edit/docs-ref-conceptual/node-howto-e2e.md) | :white_check_mark:Succeeded | |
[npm-debug.log](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/deploy-article-copy-edit/npm-debug.log) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C25%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201706251415369534-20%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by herohua** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/node-howto-e2e.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/deploy-article-copy-edit/docs-ref-conceptual/node-howto-e2e.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C25%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201706251416204531-20%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by herohua** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/node-howto-e2e.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/deploy-article-copy-edit/docs-ref-conceptual/node-howto-e2e.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C25%5Cb6261451-6613-d51e-95b5-8b5dc96f3a2c%5CPullRequest%5C201706251635196011-20%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by TomArcher** [comment]
#sign-off

**Pull request merged**
